# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the rg351p_wip branch
on:
  push:
    branches: [ rg351p_wip ]
  pull_request:
    branches: [ rg351p_wip ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt-get install sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio python unzip rsync wget bc git ncurses-base ncurses-bin ncurses-dev libncurses5-dev gcc-multilib dialog
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          make rg351p_defconfig
          make -j8
